# Generated by Django 4.1.7 on 2023-06-21 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_alter_category_options_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='Category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='description',
            new_name='discription',
        ),
    ]
