# Generated by Django 4.1.7 on 2023-06-22 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_rename_category_item_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='discription',
            new_name='description',
        ),
    ]
