# Generated by Django 4.1.7 on 2023-06-27 15:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('item', '0005_item_autor'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='watchlist',
            field=models.ManyToManyField(blank=True, null=True, related_name='User_watchlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
