# Generated by Django 4.1.7 on 2023-07-06 13:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('item', '0006_item_watchlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='watchlist',
            field=models.ManyToManyField(blank=True, related_name='User_watchlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
