# Generated by Django 4.2.5 on 2023-09-15 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_post_likepost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
